apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgresql.databases.svc.cluster.local
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    # tlsSecret: example-tls-secret
    httpEnabled: true
  ingress:
    enabled: true
    tlsSecret: example-tls-secret # TLS termination at ingress = edge mode
    annotations:
      # Ensure Traefik sets X-Forwarded-* headers correctly for TLS termination
      # Middleware reference format: namespace-name@kubernetescrd
      traefik.ingress.kubernetes.io/router.middlewares: keycloak-keycloak-headers@kubernetescrd
  hostname:
    hostname: accounts.grounds.gg
    strict: false
    strictBackchannel: false
  proxy:
    headers: xforwarded # Traefik forwards X-Forwarded-* headers

