apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocity
  namespace: games
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-gameservers
  namespace: games
rules:
  - apiGroups:
      - agones.dev
    resources:
      - gameservers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velocity-list-gameservers
  namespace: games
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-gameservers
subjects:
  - kind: ServiceAccount
    name: velocity
    namespace: games
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velocity-agones-sdk
  namespace: games
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
subjects:
  - kind: ServiceAccount
    name: velocity
    namespace: games
